/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC_interface.h"
#include "BIT_MATH.h"
#include "Stm32F103xx.h"
int main(void)
{
    /* Loop forever */
	RCC_VidInit();

	//RCC_AHBEnableClock(RCC_AHB_PERIPHERALTYPE_DMA1);
	SET_BIT(RCC->APB1ENR,7);
	RCC_APB1EnableClock(RCC_APB1_PERIPHERALTYPE_TIM14);
	for(;;);
}
